### ISSUE TITLE
Molokai egauge not responding properly through API, script throwing HTTPErrors

### ISSUE THREAD

**Issue by matthew-schultz** [erdl/lonoa#125]
It looks like the egauge on Molokai hasn't been able to connect to the internet properly since Oct 6, since the api_egauge script keeps returning HTTP errors.

Below, I've listed some example queries of the molokai database along with some of the error.log file for the molokai project's egauge script.

---
__SENSOR_INFO table__
molokai=> select purpose_id, query_string, script_folder, last_updated_datetime
from sensor_info;

 purpose_id | query_string | script_folder | last_updated_datetime 
---   |       ---     | ---   |       --- 
1 | egauge47053  | egauge        | 2019-10-06 10:29:00

---

__ERROR_LOG table example row__

molokai=> select * from error_log
order by log_id desc limit 1;

 log_id | purpose_id |        datetime        | was_success |   error_type    |   pipeline_stage   
---   |       ---     | ---   |       ---     |       ---  |  --- 
  24403 |          1 | 2019-10-24 21:30:06.98 | f           | HTTPError       | data_acquisition

---

__ERROR LOG FILE MESSAGE example__ (molokai/egauge/script/error.log)
```
10/24/2019 09:35:13 PM Egauge API data request error
Traceback (most recent call last):
  File "api_egauge.py", line 208, in <module>
    readings, purpose_sensors = get_data_from_api(conn, query_string)
  File "api_egauge.py", line 114, in get_data_from_api
    request.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://egauge47053.egaug.es/cgi-bin/egauge-show?&m&c&C&t=1570393800&f=1571988911

```

**Comment by matthew-schultz** [comment]
Closing this issue for now, since it looks like the molokai lonoa project has been pulling data from the its egauge successfully since about 12:00pm November 3rd.
